name: CTSuite
description: Connects servers under Bungeecord and offers various essential commans
main: de.crafttogether.ctsuite.bukkit.CTSuite
api-version: 1.13
version: ${project.version}
build: ${project.cibuild}
author: J0schlZ
website: ${project.url}